version: '3'
services:
  npc:
    image: npc:0.1
    ports:
      - "8080:8080"
    env_file:
      - npc.env
    networks:
      - app
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:16.0-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - app
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  app:
    driver: bridge
